### PR TITLE
Update runtime, modules, and app to latest

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by FakeShemp** [comment]
bot, build

**Comment by nielsdg** [comment]
Seahorse 3.38.0.1 has been released, so would you mind updating to that? :-)

**Comment by nielsdg** [comment]
Another question: is there a reason to add libevent?

**Comment by FakeShemp** [comment]
> Another question: is there a reason to add libevent?

Some dependency wouldn't build without it I think. I can't remember which one though.

**Review by nielsdg — APPROVED** [review]
Okay, seems to be good. Thanks! :+1:

**Pull request merged**
